name: Terraform CI
on:
    workflow_dispatch:
jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Terraform in temp VM
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Format check
              run:  terraform fmt -check -recursive 

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID}}   
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Terraform Initialization
              run: terraform init

            - name: Code Validation
              run: terraform validate

            - name: What infrastructure will be created
              env:
                TF_VAR_rg_data_name: ${{vars.RG_NAME}}
                TF_VAR_rg_data_location: ${{vars.RG_LOCATION}}
              run: terraform plan


             
